language: php
rvm :
- 5.5
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
notifications:
  email:
    - dan.perez@misena.edu.com
    on_success: always 
    on_failure: always 
